### ISSUE TITLE
selecting row with IS NULL operator

### ISSUE THREAD

**Issue by AndyFenton** [iNem0o/PicORM#6]
I am trying to find row where column canceled_at is NULL
I have tried 
Subscription::findOne(array('canceled_at' => array('operator' => 'IS NULL','value' => '')));
Subscription::findOne(array('canceled_at' => array('operator' => 'IS ','value' => 'NULL')));
Subscription::findOne(array('canceled_at' => array('operator' => 'IS NULL')));
Subscription::findOne(array('canceled_at' => array('IS NULL')));

even last one which is supposed to be RAW query. Please help me. Is it a bug? THanks

**Comment by iNem0o** [comment]
Hello @AndyFenton sorry for the late response

I will add that usage to the readme file because it is missing.

You can deal with null value with a combination of custom operator and raw SQL value. 

`$data = Test::find(['text' => ['operator' => 'IS', 'value' => ['NULL']]]);`
`$data = Test::find(['text' => ['operator' => 'IS NOT', 'value' => ['NULL']]]);`

Best regards
